### ISSUE TITLE
Creating new team

### ISSUE THREAD

**Issue by nDojic** [execom-eu/execom-labs-team-pomodoro-spring-reactjs#36]
User should automatically be a member of the team it creates. probably minor adjustment to /api/v1/team/new/{name} endpoint

**Comment by dejanjesic** [comment]
This need to be changed, team should be created through body instead of this way, through URL. So endpoint for this would be: 
POST -> /api/v1/team/new 
and body with required "teamName" field.

**Comment by nDojic** [comment]
"teamName" and "userId" or something to identify the user creating the team

**Comment by dejanjesic** [comment]
Maybe better option:

POST -> /api/v1/team

{
  * userId : "someId",
  * teamName : "someTeamName"
}

In order to avoid sufficient URL. User who creates team becomes team admin, we will add that role later on.
