### ISSUE TITLE
start pomodoro doesn't care for parameters 

### ISSUE THREAD

**Issue by nDojic** [execom-eu/execom-labs-team-pomodoro-spring-reactjs#46]
parameters for POST request for .../pomodoros/user/{userId}/start are being ignored

**Comment by b-laci** [comment]
What do you mean by that? Is the pomodoro not starting?

**Comment by nDojic** [comment]
no, it just doesn't use passed values, it starts pomodoro with default pomodoro settings ({duration:25...})

**Comment by nDojic** [comment]
my bad, it is supposed to get the parameters from query string, and not from the body.
