### ISSUE TITLE
Get members-users who are in the same teams as user with a given userId

### ISSUE THREAD

**Issue by dnilic** [execom-eu/execom-labs-team-pomodoro-spring-reactjs#65]
It would be useful to have a route with userId as a path variable - after http request is made to that route, it will result in returning the list of UserDto(s).

This list should contain all users that are in the same team(s) as a user with a given userId(without duplications - since user can be in several groups)
This is needed for logged in user, in order to be able to track current state of all teams members and their latest pomodoros.

**Comment by dnilic** [comment]
Returned list contains user with given userId too.
If we consider naming convention of new methods and purpose of the list, maybe it would be better to filter him(logged user) out from this list?

**Comment by dejanjesic** [comment]
I agree it would be more meaningful.
