### ISSUE TITLE
Send invitation that "already" exist to existing user.

### ISSUE THREAD

**Issue by dnilic** [execom-eu/execom-labs-team-pomodoro-spring-reactjs#84]
Need opinion - should we disable "creating" new invitation that already exist - combination of team_id and user_id columns in pendingInvitation table?

Currently, it is possible to send invitation to user even if invitation to join the same team is already sent.
This can be done by several different users or by one user who creates repeating invitations.
Since we do not track who sent invitation, from the aspect of invited user it is sufficient to display only one invitation.

My proposal is to disable possibility for creating new invitation if it already exist, otherwise additional filtering has to be done at frontend, especially while managing **accept** or **decline** actions...

**Comment by b-laci** [comment]
I'll fix that
